// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IronScheme.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "IronScheme.VisualStudio.19d3eb0d-b002-44a4-87f2-7d5f5b55c135";
        public const string Name = "IronScheme.VisualStudio";
        public const string Description = @"IronScheme editor extensions for Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.999.0.49";
        public const string Author = "leppie";
        public const string Tags = "ironscheme";
    }
}
