// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IronScheme.VisualStudio.REPL
{
    internal sealed partial class Vsix
    {
        public const string Id = "IronScheme.REPL.938f44b6-58bd-4801-bc8c-7f557ce99a1c";
        public const string Name = "IronScheme.REPL";
        public const string Description = @"IronScheme.REPL";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "leppie";
        public const string Tags = "";
    }
}
